quarkus:
  http:
    port: 8080
  datasource:
    db-kind: ${datasource.kind}
    jdbc:
      url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true

datasource:
  kind: h2
  url: jdbc:h2:mem:outsera
  username: outsera
  password: outsera